#!/usr/bin/env bash
# GENERATED by gen_scripts.py — do not hand-edit.
# name: audit-signal
# binary: apb
# tier: audit
# cadence: on-demand
# description: GENERATED read-only audit bundle — runs the 6 apb 'signal' diagnostic playbooks into a timestamped results dir + index.md. --only <slug,...> and --lookback supported. Zero API mutations.
# writes: never
set -euo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib/common.sh
source "${HERE}/lib/common.sh"

WATCH_NAME="audit-signal"
LOOKBACK=30
AUDIT_ONLY=""
_args=()
while [ "$#" -gt 0 ]; do
  case "$1" in
    --only) AUDIT_ONLY="${2:?--only needs a value}"; shift 2 ;;
    --only=*) AUDIT_ONLY="${1#*=}"; shift ;;
    -h|--help) audit_usage audit-signal; exit 0 ;;
    *) _args+=("$1"); shift ;;
  esac
done
parse_common_args "${_args[@]}"
audit_begin audit-signal

out="$(audit_selected capi-dual-signal && "${APB_BIN}" playbook capi-dual-signal --account "$ACCOUNT" --json --no-input --no-color 2>/dev/null || true)"; audit_record capi-dual-signal "$out"
out="$(audit_selected catalog && "${APB_BIN}" playbook catalog --account "$ACCOUNT" --json --no-input --no-color 2>/dev/null || true)"; audit_record catalog "$out"
out="$(audit_selected event-downgrade-ladder && "${APB_BIN}" playbook event-downgrade-ladder --days "$LOOKBACK" --account "$ACCOUNT" --json --no-input --no-color 2>/dev/null || true)"; audit_record event-downgrade-ladder "$out"
out="$(audit_selected event-hierarchy-audit && "${APB_BIN}" playbook event-hierarchy-audit --account "$ACCOUNT" --json --no-input --no-color 2>/dev/null || true)"; audit_record event-hierarchy-audit "$out"
out="$(audit_selected funnel-leak && "${APB_BIN}" playbook funnel-leak --days "$LOOKBACK" --account "$ACCOUNT" --json --no-input --no-color 2>/dev/null || true)"; audit_record funnel-leak "$out"
out="$(audit_selected signal-quality && "${APB_BIN}" playbook signal-quality --account "$ACCOUNT" --json --no-input --no-color 2>/dev/null || true)"; audit_record signal-quality "$out"

audit_index audit-signal
