#!/usr/bin/env bash
# GENERATED by gen_scripts.py — do not hand-edit.
# name: audit-bidding
# binary: apb
# tier: audit
# cadence: on-demand
# description: GENERATED read-only audit bundle — runs the 7 apb 'bidding' diagnostic playbooks into a timestamped results dir + index.md. --only <slug,...> and --lookback supported. Zero API mutations.
# writes: never
set -euo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib/common.sh
source "${HERE}/lib/common.sh"

WATCH_NAME="audit-bidding"
LOOKBACK=30
AUDIT_ONLY=""
_args=()
while [ "$#" -gt 0 ]; do
  case "$1" in
    --only) AUDIT_ONLY="${2:?--only needs a value}"; shift 2 ;;
    --only=*) AUDIT_ONLY="${1#*=}"; shift ;;
    -h|--help) audit_usage audit-bidding; exit 0 ;;
    *) _args+=("$1"); shift ;;
  esac
done
parse_common_args "${_args[@]}"
audit_begin audit-bidding

out="$(audit_selected bid-strategy && "${APB_BIN}" playbook bid-strategy --days "$LOOKBACK" --account "$ACCOUNT" --json --no-input --no-color 2>/dev/null || true)"; audit_record bid-strategy "$out"
out="$(audit_selected cbo-vs-abo-audit && "${APB_BIN}" playbook cbo-vs-abo-audit --days "$LOOKBACK" --account "$ACCOUNT" --json --no-input --no-color 2>/dev/null || true)"; audit_record cbo-vs-abo-audit "$out"
out="$(audit_selected delivery-pacing && "${APB_BIN}" playbook delivery-pacing --days "$LOOKBACK" --account "$ACCOUNT" --json --no-input --no-color 2>/dev/null || true)"; audit_record delivery-pacing "$out"
out="$(audit_selected learning-accelerator && "${APB_BIN}" playbook learning-accelerator --days "$LOOKBACK" --account "$ACCOUNT" --json --no-input --no-color 2>/dev/null || true)"; audit_record learning-accelerator "$out"
out="$(audit_selected rebalance && "${APB_BIN}" playbook rebalance --days "$LOOKBACK" --account "$ACCOUNT" --json --no-input --no-color 2>/dev/null || true)"; audit_record rebalance "$out"
out="$(audit_selected roas-recovery && "${APB_BIN}" playbook roas-recovery --days "$LOOKBACK" --account "$ACCOUNT" --json --no-input --no-color 2>/dev/null || true)"; audit_record roas-recovery "$out"
out="$(audit_selected scale-roadmap && "${APB_BIN}" playbook scale-roadmap --days "$LOOKBACK" --account "$ACCOUNT" --json --no-input --no-color 2>/dev/null || true)"; audit_record scale-roadmap "$out"

audit_index audit-bidding
