#!/usr/bin/env bash
# GENERATED by gen_scripts.py — do not hand-edit.
# name: audit-creative
# binary: apb
# tier: audit
# cadence: on-demand
# description: GENERATED read-only audit bundle — runs the 6 apb 'creative' diagnostic playbooks into a timestamped results dir + index.md. --only <slug,...> and --lookback supported. Zero API mutations.
# writes: never
set -euo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib/common.sh
source "${HERE}/lib/common.sh"

WATCH_NAME="audit-creative"
LOOKBACK=30
AUDIT_ONLY=""
_args=()
while [ "$#" -gt 0 ]; do
  case "$1" in
    --only) AUDIT_ONLY="${2:?--only needs a value}"; shift 2 ;;
    --only=*) AUDIT_ONLY="${1#*=}"; shift ;;
    -h|--help) audit_usage audit-creative; exit 0 ;;
    *) _args+=("$1"); shift ;;
  esac
done
parse_common_args "${_args[@]}"
audit_begin audit-creative

out="$(audit_selected creative-mix && "${APB_BIN}" playbook creative-mix --account "$ACCOUNT" --json --no-input --no-color 2>/dev/null || true)"; audit_record creative-mix "$out"
out="$(audit_selected creative-velocity && "${APB_BIN}" playbook creative-velocity --days "$LOOKBACK" --account "$ACCOUNT" --json --no-input --no-color 2>/dev/null || true)"; audit_record creative-velocity "$out"
out="$(audit_selected fatigue-index && "${APB_BIN}" playbook fatigue-index --days "$LOOKBACK" --account "$ACCOUNT" --json --no-input --no-color 2>/dev/null || true)"; audit_record fatigue-index "$out"
out="$(audit_selected placement-audit && "${APB_BIN}" playbook placement-audit --days "$LOOKBACK" --account "$ACCOUNT" --json --no-input --no-color 2>/dev/null || true)"; audit_record placement-audit "$out"
out="$(audit_selected saturation && "${APB_BIN}" playbook saturation --days "$LOOKBACK" --account "$ACCOUNT" --json --no-input --no-color 2>/dev/null || true)"; audit_record saturation "$out"
out="$(audit_selected video-engagement && "${APB_BIN}" playbook video-engagement --days "$LOOKBACK" --account "$ACCOUNT" --json --no-input --no-color 2>/dev/null || true)"; audit_record video-engagement "$out"

audit_index audit-creative
