#!/usr/bin/env bash
# GENERATED by gen_scripts.py — do not hand-edit.
# name: audit-health
# binary: apb
# tier: audit
# cadence: on-demand
# description: GENERATED read-only audit bundle — runs the 7 apb 'health' diagnostic playbooks into a timestamped results dir + index.md. --only <slug,...> and --lookback supported. Zero API mutations.
# writes: never
set -euo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib/common.sh
source "${HERE}/lib/common.sh"

WATCH_NAME="audit-health"
LOOKBACK=30
AUDIT_ONLY=""
_args=()
while [ "$#" -gt 0 ]; do
  case "$1" in
    --only) AUDIT_ONLY="${2:?--only needs a value}"; shift 2 ;;
    --only=*) AUDIT_ONLY="${1#*=}"; shift ;;
    -h|--help) audit_usage audit-health; exit 0 ;;
    *) _args+=("$1"); shift ;;
  esac
done
parse_common_args "${_args[@]}"
audit_begin audit-health

out="$(audit_selected anomaly-detect && "${APB_BIN}" playbook anomaly-detect --days "$LOOKBACK" --account "$ACCOUNT" --json --no-input --no-color 2>/dev/null || true)"; audit_record anomaly-detect "$out"
out="$(audit_selected evaluate && "${APB_BIN}" playbook evaluate --days "$LOOKBACK" --account "$ACCOUNT" --json --no-input --no-color 2>/dev/null || true)"; audit_record evaluate "$out"
out="$(audit_selected health-score && "${APB_BIN}" playbook health-score --days "$LOOKBACK" --account "$ACCOUNT" --json --no-input --no-color 2>/dev/null || true)"; audit_record health-score "$out"
out="$(audit_selected launch-check && "${APB_BIN}" playbook launch-check --account "$ACCOUNT" --json --no-input --no-color 2>/dev/null || true)"; audit_record launch-check "$out"
out="$(audit_selected no-touch-compliance && "${APB_BIN}" playbook no-touch-compliance --days "$LOOKBACK" --account "$ACCOUNT" --json --no-input --no-color 2>/dev/null || true)"; audit_record no-touch-compliance "$out"
out="$(audit_selected reset-rebuild-advisor && "${APB_BIN}" playbook reset-rebuild-advisor --days "$LOOKBACK" --account "$ACCOUNT" --json --no-input --no-color 2>/dev/null || true)"; audit_record reset-rebuild-advisor "$out"
out="$(audit_selected weekly-digest && "${APB_BIN}" playbook weekly-digest --days "$LOOKBACK" --account "$ACCOUNT" --json --no-input --no-color 2>/dev/null || true)"; audit_record weekly-digest "$out"

audit_index audit-health
