#!/usr/bin/env bash
# GENERATED by gen_scripts.py — do not hand-edit.
# name: audit-structure
# binary: apb
# tier: audit
# cadence: on-demand
# description: GENERATED read-only audit bundle — runs the 8 apb 'structure' diagnostic playbooks into a timestamped results dir + index.md. --only <slug,...> and --lookback supported. Zero API mutations.
# writes: never
set -euo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib/common.sh
source "${HERE}/lib/common.sh"

WATCH_NAME="audit-structure"
LOOKBACK=30
AUDIT_ONLY=""
_args=()
while [ "$#" -gt 0 ]; do
  case "$1" in
    --only) AUDIT_ONLY="${2:?--only needs a value}"; shift 2 ;;
    --only=*) AUDIT_ONLY="${1#*=}"; shift ;;
    -h|--help) audit_usage audit-structure; exit 0 ;;
    *) _args+=("$1"); shift ;;
  esac
done
parse_common_args "${_args[@]}"
audit_begin audit-structure

out="$(audit_selected advantage-adoption && "${APB_BIN}" playbook advantage-adoption --days "$LOOKBACK" --account "$ACCOUNT" --json --no-input --no-color 2>/dev/null || true)"; audit_record advantage-adoption "$out"
out="$(audit_selected broad-targeting-audit && "${APB_BIN}" playbook broad-targeting-audit --account "$ACCOUNT" --json --no-input --no-color 2>/dev/null || true)"; audit_record broad-targeting-audit "$out"
out="$(audit_selected consolidation-advisor && "${APB_BIN}" playbook consolidation-advisor --days "$LOOKBACK" --account "$ACCOUNT" --json --no-input --no-color 2>/dev/null || true)"; audit_record consolidation-advisor "$out"
out="$(audit_selected daypart && "${APB_BIN}" playbook daypart --days "$LOOKBACK" --account "$ACCOUNT" --json --no-input --no-color 2>/dev/null || true)"; audit_record daypart "$out"
out="$(audit_selected duplicate-detect && "${APB_BIN}" playbook duplicate-detect --days "$LOOKBACK" --account "$ACCOUNT" --json --no-input --no-color 2>/dev/null || true)"; audit_record duplicate-detect "$out"
out="$(audit_selected retargeting-compression && "${APB_BIN}" playbook retargeting-compression --account "$ACCOUNT" --json --no-input --no-color 2>/dev/null || true)"; audit_record retargeting-compression "$out"
out="$(audit_selected segment-performance && "${APB_BIN}" playbook segment-performance --days "$LOOKBACK" --account "$ACCOUNT" --json --no-input --no-color 2>/dev/null || true)"; audit_record segment-performance "$out"
out="$(audit_selected waste-audit && "${APB_BIN}" playbook waste-audit --days "$LOOKBACK" --account "$ACCOUNT" --json --no-input --no-color 2>/dev/null || true)"; audit_record waste-audit "$out"

audit_index audit-structure
