#!/usr/bin/env bash
# GENERATED by gen_scripts.py — do not hand-edit.
# name: audit-full
# binary: apb
# tier: audit
# cadence: on-demand
# description: GENERATED read-only audit bundle — runs all 34 apb diagnostic playbooks, one JSON per slug into a timestamped results dir + index.md. --only <slug,...> and --lookback supported. Zero API mutations.
# writes: never
set -euo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib/common.sh
source "${HERE}/lib/common.sh"

WATCH_NAME="audit-full"
LOOKBACK=30
AUDIT_ONLY=""
_args=()
while [ "$#" -gt 0 ]; do
  case "$1" in
    --only) AUDIT_ONLY="${2:?--only needs a value}"; shift 2 ;;
    --only=*) AUDIT_ONLY="${1#*=}"; shift ;;
    -h|--help) audit_usage audit-full; exit 0 ;;
    *) _args+=("$1"); shift ;;
  esac
done
parse_common_args "${_args[@]}"
audit_begin audit-full

out="$(audit_selected advantage-adoption && "${APB_BIN}" playbook advantage-adoption --days "$LOOKBACK" --account "$ACCOUNT" --json --no-input --no-color 2>/dev/null || true)"; audit_record advantage-adoption "$out"
out="$(audit_selected anomaly-detect && "${APB_BIN}" playbook anomaly-detect --days "$LOOKBACK" --account "$ACCOUNT" --json --no-input --no-color 2>/dev/null || true)"; audit_record anomaly-detect "$out"
out="$(audit_selected bid-strategy && "${APB_BIN}" playbook bid-strategy --days "$LOOKBACK" --account "$ACCOUNT" --json --no-input --no-color 2>/dev/null || true)"; audit_record bid-strategy "$out"
out="$(audit_selected broad-targeting-audit && "${APB_BIN}" playbook broad-targeting-audit --account "$ACCOUNT" --json --no-input --no-color 2>/dev/null || true)"; audit_record broad-targeting-audit "$out"
out="$(audit_selected capi-dual-signal && "${APB_BIN}" playbook capi-dual-signal --account "$ACCOUNT" --json --no-input --no-color 2>/dev/null || true)"; audit_record capi-dual-signal "$out"
out="$(audit_selected catalog && "${APB_BIN}" playbook catalog --account "$ACCOUNT" --json --no-input --no-color 2>/dev/null || true)"; audit_record catalog "$out"
out="$(audit_selected cbo-vs-abo-audit && "${APB_BIN}" playbook cbo-vs-abo-audit --days "$LOOKBACK" --account "$ACCOUNT" --json --no-input --no-color 2>/dev/null || true)"; audit_record cbo-vs-abo-audit "$out"
out="$(audit_selected consolidation-advisor && "${APB_BIN}" playbook consolidation-advisor --days "$LOOKBACK" --account "$ACCOUNT" --json --no-input --no-color 2>/dev/null || true)"; audit_record consolidation-advisor "$out"
out="$(audit_selected creative-mix && "${APB_BIN}" playbook creative-mix --account "$ACCOUNT" --json --no-input --no-color 2>/dev/null || true)"; audit_record creative-mix "$out"
out="$(audit_selected creative-velocity && "${APB_BIN}" playbook creative-velocity --days "$LOOKBACK" --account "$ACCOUNT" --json --no-input --no-color 2>/dev/null || true)"; audit_record creative-velocity "$out"
out="$(audit_selected daypart && "${APB_BIN}" playbook daypart --days "$LOOKBACK" --account "$ACCOUNT" --json --no-input --no-color 2>/dev/null || true)"; audit_record daypart "$out"
out="$(audit_selected delivery-pacing && "${APB_BIN}" playbook delivery-pacing --days "$LOOKBACK" --account "$ACCOUNT" --json --no-input --no-color 2>/dev/null || true)"; audit_record delivery-pacing "$out"
out="$(audit_selected duplicate-detect && "${APB_BIN}" playbook duplicate-detect --days "$LOOKBACK" --account "$ACCOUNT" --json --no-input --no-color 2>/dev/null || true)"; audit_record duplicate-detect "$out"
out="$(audit_selected evaluate && "${APB_BIN}" playbook evaluate --days "$LOOKBACK" --account "$ACCOUNT" --json --no-input --no-color 2>/dev/null || true)"; audit_record evaluate "$out"
out="$(audit_selected event-downgrade-ladder && "${APB_BIN}" playbook event-downgrade-ladder --days "$LOOKBACK" --account "$ACCOUNT" --json --no-input --no-color 2>/dev/null || true)"; audit_record event-downgrade-ladder "$out"
out="$(audit_selected event-hierarchy-audit && "${APB_BIN}" playbook event-hierarchy-audit --account "$ACCOUNT" --json --no-input --no-color 2>/dev/null || true)"; audit_record event-hierarchy-audit "$out"
out="$(audit_selected fatigue-index && "${APB_BIN}" playbook fatigue-index --days "$LOOKBACK" --account "$ACCOUNT" --json --no-input --no-color 2>/dev/null || true)"; audit_record fatigue-index "$out"
out="$(audit_selected funnel-leak && "${APB_BIN}" playbook funnel-leak --days "$LOOKBACK" --account "$ACCOUNT" --json --no-input --no-color 2>/dev/null || true)"; audit_record funnel-leak "$out"
out="$(audit_selected health-score && "${APB_BIN}" playbook health-score --days "$LOOKBACK" --account "$ACCOUNT" --json --no-input --no-color 2>/dev/null || true)"; audit_record health-score "$out"
out="$(audit_selected launch-check && "${APB_BIN}" playbook launch-check --account "$ACCOUNT" --json --no-input --no-color 2>/dev/null || true)"; audit_record launch-check "$out"
out="$(audit_selected learning-accelerator && "${APB_BIN}" playbook learning-accelerator --days "$LOOKBACK" --account "$ACCOUNT" --json --no-input --no-color 2>/dev/null || true)"; audit_record learning-accelerator "$out"
out="$(audit_selected no-touch-compliance && "${APB_BIN}" playbook no-touch-compliance --days "$LOOKBACK" --account "$ACCOUNT" --json --no-input --no-color 2>/dev/null || true)"; audit_record no-touch-compliance "$out"
out="$(audit_selected placement-audit && "${APB_BIN}" playbook placement-audit --days "$LOOKBACK" --account "$ACCOUNT" --json --no-input --no-color 2>/dev/null || true)"; audit_record placement-audit "$out"
out="$(audit_selected rebalance && "${APB_BIN}" playbook rebalance --days "$LOOKBACK" --account "$ACCOUNT" --json --no-input --no-color 2>/dev/null || true)"; audit_record rebalance "$out"
out="$(audit_selected reset-rebuild-advisor && "${APB_BIN}" playbook reset-rebuild-advisor --days "$LOOKBACK" --account "$ACCOUNT" --json --no-input --no-color 2>/dev/null || true)"; audit_record reset-rebuild-advisor "$out"
out="$(audit_selected retargeting-compression && "${APB_BIN}" playbook retargeting-compression --account "$ACCOUNT" --json --no-input --no-color 2>/dev/null || true)"; audit_record retargeting-compression "$out"
out="$(audit_selected roas-recovery && "${APB_BIN}" playbook roas-recovery --days "$LOOKBACK" --account "$ACCOUNT" --json --no-input --no-color 2>/dev/null || true)"; audit_record roas-recovery "$out"
out="$(audit_selected saturation && "${APB_BIN}" playbook saturation --days "$LOOKBACK" --account "$ACCOUNT" --json --no-input --no-color 2>/dev/null || true)"; audit_record saturation "$out"
out="$(audit_selected scale-roadmap && "${APB_BIN}" playbook scale-roadmap --days "$LOOKBACK" --account "$ACCOUNT" --json --no-input --no-color 2>/dev/null || true)"; audit_record scale-roadmap "$out"
out="$(audit_selected segment-performance && "${APB_BIN}" playbook segment-performance --days "$LOOKBACK" --account "$ACCOUNT" --json --no-input --no-color 2>/dev/null || true)"; audit_record segment-performance "$out"
out="$(audit_selected signal-quality && "${APB_BIN}" playbook signal-quality --account "$ACCOUNT" --json --no-input --no-color 2>/dev/null || true)"; audit_record signal-quality "$out"
out="$(audit_selected video-engagement && "${APB_BIN}" playbook video-engagement --days "$LOOKBACK" --account "$ACCOUNT" --json --no-input --no-color 2>/dev/null || true)"; audit_record video-engagement "$out"
out="$(audit_selected waste-audit && "${APB_BIN}" playbook waste-audit --days "$LOOKBACK" --account "$ACCOUNT" --json --no-input --no-color 2>/dev/null || true)"; audit_record waste-audit "$out"
out="$(audit_selected weekly-digest && "${APB_BIN}" playbook weekly-digest --days "$LOOKBACK" --account "$ACCOUNT" --json --no-input --no-color 2>/dev/null || true)"; audit_record weekly-digest "$out"

audit_index audit-full
