#!/usr/bin/env bash
# GENERATED by gen_scripts.py — do not hand-edit.
# name: audit-keywords
# binary: apb-gads
# tier: audit
# cadence: on-demand
# description: GENERATED read-only audit bundle — runs the 13 apb-gads 'keywords' diagnostic playbooks into a timestamped results dir + index.md. --only <slug,...> and --lookback supported. Zero API mutations.
# writes: never
set -euo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib/common.sh
source "${HERE}/lib/common.sh"

WATCH_NAME="audit-keywords"
LOOKBACK=30
AUDIT_ONLY=""
_args=()
while [ "$#" -gt 0 ]; do
  case "$1" in
    --only) AUDIT_ONLY="${2:?--only needs a value}"; shift 2 ;;
    --only=*) AUDIT_ONLY="${1#*=}"; shift ;;
    -h|--help) audit_usage audit-keywords; exit 0 ;;
    *) _args+=("$1"); shift ;;
  esac
done
parse_common_args "${_args[@]}"
audit_begin audit-keywords

out="$(audit_selected broad-match-conversion-rate && "${APB_GADS_BIN}" ${GADS_EXTRA_ARGS} --customer "$CUSTOMER" playbook broad-match-conversion-rate --lookback-days "$LOOKBACK" 2>/dev/null || true)"; audit_record broad-match-conversion-rate "$out"
out="$(audit_selected competitor-keyword-bleed && "${APB_GADS_BIN}" ${GADS_EXTRA_ARGS} --customer "$CUSTOMER" playbook competitor-keyword-bleed --lookback-days "$LOOKBACK" 2>/dev/null || true)"; audit_record competitor-keyword-bleed "$out"
out="$(audit_selected duplicate-keywords && "${APB_GADS_BIN}" ${GADS_EXTRA_ARGS} --customer "$CUSTOMER" playbook duplicate-keywords --lookback-days "$LOOKBACK" 2>/dev/null || true)"; audit_record duplicate-keywords "$out"
out="$(audit_selected keyword-match-type-mix && "${APB_GADS_BIN}" ${GADS_EXTRA_ARGS} --customer "$CUSTOMER" playbook keyword-match-type-mix --lookback-days "$LOOKBACK" 2>/dev/null || true)"; audit_record keyword-match-type-mix "$out"
out="$(audit_selected keyword-prune-audit && "${APB_GADS_BIN}" ${GADS_EXTRA_ARGS} --customer "$CUSTOMER" playbook keyword-prune-audit --lookback-days "$LOOKBACK" 2>/dev/null || true)"; audit_record keyword-prune-audit "$out"
out="$(audit_selected match-type-sculpting && "${APB_GADS_BIN}" ${GADS_EXTRA_ARGS} --customer "$CUSTOMER" playbook match-type-sculpting --lookback-days "$LOOKBACK" 2>/dev/null || true)"; audit_record match-type-sculpting "$out"
out="$(audit_selected negative-keyword-coverage && "${APB_GADS_BIN}" ${GADS_EXTRA_ARGS} --customer "$CUSTOMER" playbook negative-keyword-coverage --lookback-days "$LOOKBACK" 2>/dev/null || true)"; audit_record negative-keyword-coverage "$out"
out="$(audit_selected search-term-analysis && "${APB_GADS_BIN}" ${GADS_EXTRA_ARGS} --customer "$CUSTOMER" playbook search-term-analysis --lookback-days "$LOOKBACK" 2>/dev/null || true)"; audit_record search-term-analysis "$out"
out="$(audit_selected search-term-cleanup && "${APB_GADS_BIN}" ${GADS_EXTRA_ARGS} --customer "$CUSTOMER" playbook search-term-cleanup --lookback-days "$LOOKBACK" 2>/dev/null || true)"; audit_record search-term-cleanup "$out"
out="$(audit_selected search-term-ngram-audit && "${APB_GADS_BIN}" ${GADS_EXTRA_ARGS} --customer "$CUSTOMER" playbook search-term-ngram-audit --lookback-days "$LOOKBACK" 2>/dev/null || true)"; audit_record search-term-ngram-audit "$out"
out="$(audit_selected search-term-promotion && "${APB_GADS_BIN}" ${GADS_EXTRA_ARGS} --customer "$CUSTOMER" playbook search-term-promotion --lookback-days "$LOOKBACK" 2>/dev/null || true)"; audit_record search-term-promotion "$out"
out="$(audit_selected waste-audit && "${APB_GADS_BIN}" ${GADS_EXTRA_ARGS} --customer "$CUSTOMER" playbook waste-audit --lookback-days "$LOOKBACK" 2>/dev/null || true)"; audit_record waste-audit "$out"
out="$(audit_selected waste-cluster-audit && "${APB_GADS_BIN}" ${GADS_EXTRA_ARGS} --customer "$CUSTOMER" playbook waste-cluster-audit --lookback-days "$LOOKBACK" 2>/dev/null || true)"; audit_record waste-cluster-audit "$out"

audit_index audit-keywords
