#!/usr/bin/env bash
# GENERATED by gen_scripts.py — do not hand-edit.
# name: audit-other
# binary: apb-gads
# tier: audit
# cadence: on-demand
# description: GENERATED read-only audit bundle — runs the 1 apb-gads 'other' diagnostic playbooks into a timestamped results dir + index.md. --only <slug,...> and --lookback supported. Zero API mutations.
# writes: never
set -euo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib/common.sh
source "${HERE}/lib/common.sh"

WATCH_NAME="audit-other"
LOOKBACK=30
AUDIT_ONLY=""
_args=()
while [ "$#" -gt 0 ]; do
  case "$1" in
    --only) AUDIT_ONLY="${2:?--only needs a value}"; shift 2 ;;
    --only=*) AUDIT_ONLY="${1#*=}"; shift ;;
    -h|--help) audit_usage audit-other; exit 0 ;;
    *) _args+=("$1"); shift ;;
  esac
done
parse_common_args "${_args[@]}"
audit_begin audit-other

out="$(audit_selected feed-health-audit && "${APB_GADS_BIN}" ${GADS_EXTRA_ARGS} --customer "$CUSTOMER" playbook feed-health-audit --lookback-days "$LOOKBACK" 2>/dev/null || true)"; audit_record feed-health-audit "$out"

audit_index audit-other
