#!/usr/bin/env bash
# GENERATED by gen_scripts.py — do not hand-edit.
# name: audit-pmax
# binary: apb-gads
# tier: audit
# cadence: on-demand
# description: GENERATED read-only audit bundle — runs the 6 apb-gads 'pmax' diagnostic playbooks into a timestamped results dir + index.md. --only <slug,...> and --lookback supported. Zero API mutations.
# writes: never
set -euo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib/common.sh
source "${HERE}/lib/common.sh"

WATCH_NAME="audit-pmax"
LOOKBACK=30
AUDIT_ONLY=""
_args=()
while [ "$#" -gt 0 ]; do
  case "$1" in
    --only) AUDIT_ONLY="${2:?--only needs a value}"; shift 2 ;;
    --only=*) AUDIT_ONLY="${1#*=}"; shift ;;
    -h|--help) audit_usage audit-pmax; exit 0 ;;
    *) _args+=("$1"); shift ;;
  esac
done
parse_common_args "${_args[@]}"
audit_begin audit-pmax

out="$(audit_selected pmax-asset-coverage && "${APB_GADS_BIN}" ${GADS_EXTRA_ARGS} --customer "$CUSTOMER" playbook pmax-asset-coverage --lookback-days "$LOOKBACK" 2>/dev/null || true)"; audit_record pmax-asset-coverage "$out"
out="$(audit_selected pmax-audit && "${APB_GADS_BIN}" ${GADS_EXTRA_ARGS} --customer "$CUSTOMER" playbook pmax-audit --lookback-days "$LOOKBACK" 2>/dev/null || true)"; audit_record pmax-audit "$out"
out="$(audit_selected pmax-maturity-gate && "${APB_GADS_BIN}" ${GADS_EXTRA_ARGS} --customer "$CUSTOMER" playbook pmax-maturity-gate --lookback-days "$LOOKBACK" 2>/dev/null || true)"; audit_record pmax-maturity-gate "$out"
out="$(audit_selected pmax-scaling-plan && "${APB_GADS_BIN}" ${GADS_EXTRA_ARGS} --customer "$CUSTOMER" playbook pmax-scaling-plan --lookback-days "$LOOKBACK" 2>/dev/null || true)"; audit_record pmax-scaling-plan "$out"
out="$(audit_selected pmax-segmentation-audit && "${APB_GADS_BIN}" ${GADS_EXTRA_ARGS} --customer "$CUSTOMER" playbook pmax-segmentation-audit --lookback-days "$LOOKBACK" 2>/dev/null || true)"; audit_record pmax-segmentation-audit "$out"
out="$(audit_selected pmax-url-exclusion-audit && "${APB_GADS_BIN}" ${GADS_EXTRA_ARGS} --customer "$CUSTOMER" playbook pmax-url-exclusion-audit --lookback-days "$LOOKBACK" 2>/dev/null || true)"; audit_record pmax-url-exclusion-audit "$out"

audit_index audit-pmax
