#!/usr/bin/env bash
# GENERATED by gen_scripts.py — do not hand-edit.
# name: audit-creative
# binary: apb-gads
# tier: audit
# cadence: on-demand
# description: GENERATED read-only audit bundle — runs the 7 apb-gads 'creative' diagnostic playbooks into a timestamped results dir + index.md. --only <slug,...> and --lookback supported. Zero API mutations.
# writes: never
set -euo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib/common.sh
source "${HERE}/lib/common.sh"

WATCH_NAME="audit-creative"
LOOKBACK=30
AUDIT_ONLY=""
_args=()
while [ "$#" -gt 0 ]; do
  case "$1" in
    --only) AUDIT_ONLY="${2:?--only needs a value}"; shift 2 ;;
    --only=*) AUDIT_ONLY="${1#*=}"; shift ;;
    -h|--help) audit_usage audit-creative; exit 0 ;;
    *) _args+=("$1"); shift ;;
  esac
done
parse_common_args "${_args[@]}"
audit_begin audit-creative

out="$(audit_selected ad-extension-coverage && "${APB_GADS_BIN}" ${GADS_EXTRA_ARGS} --customer "$CUSTOMER" playbook ad-extension-coverage --lookback-days "$LOOKBACK" 2>/dev/null || true)"; audit_record ad-extension-coverage "$out"
out="$(audit_selected ad-rotation-audit && "${APB_GADS_BIN}" ${GADS_EXTRA_ARGS} --customer "$CUSTOMER" playbook ad-rotation-audit --lookback-days "$LOOKBACK" 2>/dev/null || true)"; audit_record ad-rotation-audit "$out"
out="$(audit_selected creative-refresh && "${APB_GADS_BIN}" ${GADS_EXTRA_ARGS} --customer "$CUSTOMER" playbook creative-refresh --lookback-days "$LOOKBACK" 2>/dev/null || true)"; audit_record creative-refresh "$out"
out="$(audit_selected landing-page-audit && "${APB_GADS_BIN}" ${GADS_EXTRA_ARGS} --customer "$CUSTOMER" playbook landing-page-audit --lookback-days "$LOOKBACK" 2>/dev/null || true)"; audit_record landing-page-audit "$out"
out="$(audit_selected landing-page-intent-drift-audit && "${APB_GADS_BIN}" ${GADS_EXTRA_ARGS} --customer "$CUSTOMER" playbook landing-page-intent-drift-audit --lookback-days "$LOOKBACK" 2>/dev/null || true)"; audit_record landing-page-intent-drift-audit "$out"
out="$(audit_selected rsa-asset-performance && "${APB_GADS_BIN}" ${GADS_EXTRA_ARGS} --customer "$CUSTOMER" playbook rsa-asset-performance --lookback-days "$LOOKBACK" 2>/dev/null || true)"; audit_record rsa-asset-performance "$out"
out="$(audit_selected rsa-quality-audit && "${APB_GADS_BIN}" ${GADS_EXTRA_ARGS} --customer "$CUSTOMER" playbook rsa-quality-audit --lookback-days "$LOOKBACK" 2>/dev/null || true)"; audit_record rsa-quality-audit "$out"

audit_index audit-creative
