#!/usr/bin/env bash
# GENERATED by gen_scripts.py — do not hand-edit.
# name: audit-full
# binary: apb-gads
# tier: audit
# cadence: on-demand
# description: GENERATED read-only audit bundle — runs all 66 apb-gads diagnostic playbooks, one JSON per slug into a timestamped results dir + index.md. --only <slug,...> and --lookback supported. Zero API mutations.
# writes: never
set -euo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib/common.sh
source "${HERE}/lib/common.sh"

WATCH_NAME="audit-full"
LOOKBACK=30
AUDIT_ONLY=""
_args=()
while [ "$#" -gt 0 ]; do
  case "$1" in
    --only) AUDIT_ONLY="${2:?--only needs a value}"; shift 2 ;;
    --only=*) AUDIT_ONLY="${1#*=}"; shift ;;
    -h|--help) audit_usage audit-full; exit 0 ;;
    *) _args+=("$1"); shift ;;
  esac
done
parse_common_args "${_args[@]}"
audit_begin audit-full

out="$(audit_selected account-health && "${APB_GADS_BIN}" ${GADS_EXTRA_ARGS} --customer "$CUSTOMER" playbook account-health --lookback-days "$LOOKBACK" 2>/dev/null || true)"; audit_record account-health "$out"
out="$(audit_selected account-structure-audit && "${APB_GADS_BIN}" ${GADS_EXTRA_ARGS} --customer "$CUSTOMER" playbook account-structure-audit --lookback-days "$LOOKBACK" 2>/dev/null || true)"; audit_record account-structure-audit "$out"
out="$(audit_selected ad-extension-coverage && "${APB_GADS_BIN}" ${GADS_EXTRA_ARGS} --customer "$CUSTOMER" playbook ad-extension-coverage --lookback-days "$LOOKBACK" 2>/dev/null || true)"; audit_record ad-extension-coverage "$out"
out="$(audit_selected ad-rotation-audit && "${APB_GADS_BIN}" ${GADS_EXTRA_ARGS} --customer "$CUSTOMER" playbook ad-rotation-audit --lookback-days "$LOOKBACK" 2>/dev/null || true)"; audit_record ad-rotation-audit "$out"
out="$(audit_selected anomaly-detection && "${APB_GADS_BIN}" ${GADS_EXTRA_ARGS} --customer "$CUSTOMER" playbook anomaly-detection --lookback-days "$LOOKBACK" 2>/dev/null || true)"; audit_record anomaly-detection "$out"
out="$(audit_selected audience-burnout-detection && "${APB_GADS_BIN}" ${GADS_EXTRA_ARGS} --customer "$CUSTOMER" playbook audience-burnout-detection --lookback-days "$LOOKBACK" 2>/dev/null || true)"; audit_record audience-burnout-detection "$out"
out="$(audit_selected audience-performance && "${APB_GADS_BIN}" ${GADS_EXTRA_ARGS} --customer "$CUSTOMER" playbook audience-performance --lookback-days "$LOOKBACK" 2>/dev/null || true)"; audit_record audience-performance "$out"
out="$(audit_selected bid-strategy-mismatch && "${APB_GADS_BIN}" ${GADS_EXTRA_ARGS} --customer "$CUSTOMER" playbook bid-strategy-mismatch --lookback-days "$LOOKBACK" 2>/dev/null || true)"; audit_record bid-strategy-mismatch "$out"
out="$(audit_selected brand-exclusion-audit && "${APB_GADS_BIN}" ${GADS_EXTRA_ARGS} --customer "$CUSTOMER" playbook brand-exclusion-audit --lookback-days "$LOOKBACK" 2>/dev/null || true)"; audit_record brand-exclusion-audit "$out"
out="$(audit_selected broad-match-conversion-rate && "${APB_GADS_BIN}" ${GADS_EXTRA_ARGS} --customer "$CUSTOMER" playbook broad-match-conversion-rate --lookback-days "$LOOKBACK" 2>/dev/null || true)"; audit_record broad-match-conversion-rate "$out"
out="$(audit_selected budget-pacing && "${APB_GADS_BIN}" ${GADS_EXTRA_ARGS} --customer "$CUSTOMER" playbook budget-pacing --lookback-days "$LOOKBACK" 2>/dev/null || true)"; audit_record budget-pacing "$out"
out="$(audit_selected budget-rebalance && "${APB_GADS_BIN}" ${GADS_EXTRA_ARGS} --customer "$CUSTOMER" playbook budget-rebalance --lookback-days "$LOOKBACK" 2>/dev/null || true)"; audit_record budget-rebalance "$out"
out="$(audit_selected campaign-bid-strategy-audit && "${APB_GADS_BIN}" ${GADS_EXTRA_ARGS} --customer "$CUSTOMER" playbook campaign-bid-strategy-audit --lookback-days "$LOOKBACK" 2>/dev/null || true)"; audit_record campaign-bid-strategy-audit "$out"
out="$(audit_selected campaign-cannibalization && "${APB_GADS_BIN}" ${GADS_EXTRA_ARGS} --customer "$CUSTOMER" playbook campaign-cannibalization --lookback-days "$LOOKBACK" 2>/dev/null || true)"; audit_record campaign-cannibalization "$out"
out="$(audit_selected campaign-consolidation-audit && "${APB_GADS_BIN}" ${GADS_EXTRA_ARGS} --customer "$CUSTOMER" playbook campaign-consolidation-audit --lookback-days "$LOOKBACK" 2>/dev/null || true)"; audit_record campaign-consolidation-audit "$out"
out="$(audit_selected campaign-type-fit && "${APB_GADS_BIN}" ${GADS_EXTRA_ARGS} --customer "$CUSTOMER" playbook campaign-type-fit --lookback-days "$LOOKBACK" 2>/dev/null || true)"; audit_record campaign-type-fit "$out"
out="$(audit_selected competitor-keyword-bleed && "${APB_GADS_BIN}" ${GADS_EXTRA_ARGS} --customer "$CUSTOMER" playbook competitor-keyword-bleed --lookback-days "$LOOKBACK" 2>/dev/null || true)"; audit_record competitor-keyword-bleed "$out"
out="$(audit_selected competitor-pressure && "${APB_GADS_BIN}" ${GADS_EXTRA_ARGS} --customer "$CUSTOMER" playbook competitor-pressure --lookback-days "$LOOKBACK" 2>/dev/null || true)"; audit_record competitor-pressure "$out"
out="$(audit_selected conversion-tracking-audit && "${APB_GADS_BIN}" ${GADS_EXTRA_ARGS} --customer "$CUSTOMER" playbook conversion-tracking-audit --lookback-days "$LOOKBACK" 2>/dev/null || true)"; audit_record conversion-tracking-audit "$out"
out="$(audit_selected conversion-tracking-check && "${APB_GADS_BIN}" ${GADS_EXTRA_ARGS} --customer "$CUSTOMER" playbook conversion-tracking-check --lookback-days "$LOOKBACK" 2>/dev/null || true)"; audit_record conversion-tracking-check "$out"
out="$(audit_selected conversion-value-gap && "${APB_GADS_BIN}" ${GADS_EXTRA_ARGS} --customer "$CUSTOMER" playbook conversion-value-gap --lookback-days "$LOOKBACK" 2>/dev/null || true)"; audit_record conversion-value-gap "$out"
out="$(audit_selected conversion-value-tier-audit && "${APB_GADS_BIN}" ${GADS_EXTRA_ARGS} --customer "$CUSTOMER" playbook conversion-value-tier-audit --lookback-days "$LOOKBACK" 2>/dev/null || true)"; audit_record conversion-value-tier-audit "$out"
out="$(audit_selected creative-refresh && "${APB_GADS_BIN}" ${GADS_EXTRA_ARGS} --customer "$CUSTOMER" playbook creative-refresh --lookback-days "$LOOKBACK" 2>/dev/null || true)"; audit_record creative-refresh "$out"
out="$(audit_selected cross-network-performance && "${APB_GADS_BIN}" ${GADS_EXTRA_ARGS} --customer "$CUSTOMER" playbook cross-network-performance --lookback-days "$LOOKBACK" 2>/dev/null || true)"; audit_record cross-network-performance "$out"
out="$(audit_selected dayparting-analysis && "${APB_GADS_BIN}" ${GADS_EXTRA_ARGS} --customer "$CUSTOMER" playbook dayparting-analysis --lookback-days "$LOOKBACK" 2>/dev/null || true)"; audit_record dayparting-analysis "$out"
out="$(audit_selected device-performance && "${APB_GADS_BIN}" ${GADS_EXTRA_ARGS} --customer "$CUSTOMER" playbook device-performance --lookback-days "$LOOKBACK" 2>/dev/null || true)"; audit_record device-performance "$out"
out="$(audit_selected duplicate-keywords && "${APB_GADS_BIN}" ${GADS_EXTRA_ARGS} --customer "$CUSTOMER" playbook duplicate-keywords --lookback-days "$LOOKBACK" 2>/dev/null || true)"; audit_record duplicate-keywords "$out"
out="$(audit_selected expansion-readiness && "${APB_GADS_BIN}" ${GADS_EXTRA_ARGS} --customer "$CUSTOMER" playbook expansion-readiness --lookback-days "$LOOKBACK" 2>/dev/null || true)"; audit_record expansion-readiness "$out"
out="$(audit_selected experiment-readiness && "${APB_GADS_BIN}" ${GADS_EXTRA_ARGS} --customer "$CUSTOMER" playbook experiment-readiness --lookback-days "$LOOKBACK" 2>/dev/null || true)"; audit_record experiment-readiness "$out"
out="$(audit_selected geo-bid-drift-audit && "${APB_GADS_BIN}" ${GADS_EXTRA_ARGS} --customer "$CUSTOMER" playbook geo-bid-drift-audit --lookback-days "$LOOKBACK" 2>/dev/null || true)"; audit_record geo-bid-drift-audit "$out"
out="$(audit_selected geo-performance && "${APB_GADS_BIN}" ${GADS_EXTRA_ARGS} --customer "$CUSTOMER" playbook geo-performance --lookback-days "$LOOKBACK" 2>/dev/null || true)"; audit_record geo-performance "$out"
out="$(audit_selected impression-share-loss && "${APB_GADS_BIN}" ${GADS_EXTRA_ARGS} --customer "$CUSTOMER" playbook impression-share-loss --lookback-days "$LOOKBACK" 2>/dev/null || true)"; audit_record impression-share-loss "$out"
out="$(audit_selected keyword-match-type-mix && "${APB_GADS_BIN}" ${GADS_EXTRA_ARGS} --customer "$CUSTOMER" playbook keyword-match-type-mix --lookback-days "$LOOKBACK" 2>/dev/null || true)"; audit_record keyword-match-type-mix "$out"
out="$(audit_selected keyword-prune-audit && "${APB_GADS_BIN}" ${GADS_EXTRA_ARGS} --customer "$CUSTOMER" playbook keyword-prune-audit --lookback-days "$LOOKBACK" 2>/dev/null || true)"; audit_record keyword-prune-audit "$out"
out="$(audit_selected landing-page-audit && "${APB_GADS_BIN}" ${GADS_EXTRA_ARGS} --customer "$CUSTOMER" playbook landing-page-audit --lookback-days "$LOOKBACK" 2>/dev/null || true)"; audit_record landing-page-audit "$out"
out="$(audit_selected landing-page-intent-drift-audit && "${APB_GADS_BIN}" ${GADS_EXTRA_ARGS} --customer "$CUSTOMER" playbook landing-page-intent-drift-audit --lookback-days "$LOOKBACK" 2>/dev/null || true)"; audit_record landing-page-intent-drift-audit "$out"
out="$(audit_selected launch-check && "${APB_GADS_BIN}" ${GADS_EXTRA_ARGS} --customer "$CUSTOMER" playbook launch-check --lookback-days "$LOOKBACK" 2>/dev/null || true)"; audit_record launch-check "$out"
out="$(audit_selected match-type-sculpting && "${APB_GADS_BIN}" ${GADS_EXTRA_ARGS} --customer "$CUSTOMER" playbook match-type-sculpting --lookback-days "$LOOKBACK" 2>/dev/null || true)"; audit_record match-type-sculpting "$out"
out="$(audit_selected naming-convention-audit && "${APB_GADS_BIN}" ${GADS_EXTRA_ARGS} --customer "$CUSTOMER" playbook naming-convention-audit --lookback-days "$LOOKBACK" 2>/dev/null || true)"; audit_record naming-convention-audit "$out"
out="$(audit_selected negative-keyword-coverage && "${APB_GADS_BIN}" ${GADS_EXTRA_ARGS} --customer "$CUSTOMER" playbook negative-keyword-coverage --lookback-days "$LOOKBACK" 2>/dev/null || true)"; audit_record negative-keyword-coverage "$out"
out="$(audit_selected placement-leakage-audit && "${APB_GADS_BIN}" ${GADS_EXTRA_ARGS} --customer "$CUSTOMER" playbook placement-leakage-audit --lookback-days "$LOOKBACK" 2>/dev/null || true)"; audit_record placement-leakage-audit "$out"
out="$(audit_selected pmax-asset-coverage && "${APB_GADS_BIN}" ${GADS_EXTRA_ARGS} --customer "$CUSTOMER" playbook pmax-asset-coverage --lookback-days "$LOOKBACK" 2>/dev/null || true)"; audit_record pmax-asset-coverage "$out"
out="$(audit_selected pmax-audit && "${APB_GADS_BIN}" ${GADS_EXTRA_ARGS} --customer "$CUSTOMER" playbook pmax-audit --lookback-days "$LOOKBACK" 2>/dev/null || true)"; audit_record pmax-audit "$out"
out="$(audit_selected pmax-maturity-gate && "${APB_GADS_BIN}" ${GADS_EXTRA_ARGS} --customer "$CUSTOMER" playbook pmax-maturity-gate --lookback-days "$LOOKBACK" 2>/dev/null || true)"; audit_record pmax-maturity-gate "$out"
out="$(audit_selected pmax-scaling-plan && "${APB_GADS_BIN}" ${GADS_EXTRA_ARGS} --customer "$CUSTOMER" playbook pmax-scaling-plan --lookback-days "$LOOKBACK" 2>/dev/null || true)"; audit_record pmax-scaling-plan "$out"
out="$(audit_selected pmax-segmentation-audit && "${APB_GADS_BIN}" ${GADS_EXTRA_ARGS} --customer "$CUSTOMER" playbook pmax-segmentation-audit --lookback-days "$LOOKBACK" 2>/dev/null || true)"; audit_record pmax-segmentation-audit "$out"
out="$(audit_selected pmax-url-exclusion-audit && "${APB_GADS_BIN}" ${GADS_EXTRA_ARGS} --customer "$CUSTOMER" playbook pmax-url-exclusion-audit --lookback-days "$LOOKBACK" 2>/dev/null || true)"; audit_record pmax-url-exclusion-audit "$out"
out="$(audit_selected policy-compliance && "${APB_GADS_BIN}" ${GADS_EXTRA_ARGS} --customer "$CUSTOMER" playbook policy-compliance --lookback-days "$LOOKBACK" 2>/dev/null || true)"; audit_record policy-compliance "$out"
out="$(audit_selected qs-cpc-tax && "${APB_GADS_BIN}" ${GADS_EXTRA_ARGS} --customer "$CUSTOMER" playbook qs-cpc-tax --lookback-days "$LOOKBACK" 2>/dev/null || true)"; audit_record qs-cpc-tax "$out"
out="$(audit_selected quality-score-audit && "${APB_GADS_BIN}" ${GADS_EXTRA_ARGS} --customer "$CUSTOMER" playbook quality-score-audit --lookback-days "$LOOKBACK" 2>/dev/null || true)"; audit_record quality-score-audit "$out"
out="$(audit_selected quality-score-root-cause && "${APB_GADS_BIN}" ${GADS_EXTRA_ARGS} --customer "$CUSTOMER" playbook quality-score-root-cause --lookback-days "$LOOKBACK" 2>/dev/null || true)"; audit_record quality-score-root-cause "$out"
out="$(audit_selected roas-nudge-recommendation && "${APB_GADS_BIN}" ${GADS_EXTRA_ARGS} --customer "$CUSTOMER" playbook roas-nudge-recommendation --lookback-days "$LOOKBACK" 2>/dev/null || true)"; audit_record roas-nudge-recommendation "$out"
out="$(audit_selected rsa-asset-performance && "${APB_GADS_BIN}" ${GADS_EXTRA_ARGS} --customer "$CUSTOMER" playbook rsa-asset-performance --lookback-days "$LOOKBACK" 2>/dev/null || true)"; audit_record rsa-asset-performance "$out"
out="$(audit_selected rsa-quality-audit && "${APB_GADS_BIN}" ${GADS_EXTRA_ARGS} --customer "$CUSTOMER" playbook rsa-quality-audit --lookback-days "$LOOKBACK" 2>/dev/null || true)"; audit_record rsa-quality-audit "$out"
out="$(audit_selected sandbox-campaign-audit && "${APB_GADS_BIN}" ${GADS_EXTRA_ARGS} --customer "$CUSTOMER" playbook sandbox-campaign-audit --lookback-days "$LOOKBACK" 2>/dev/null || true)"; audit_record sandbox-campaign-audit "$out"
out="$(audit_selected search-term-analysis && "${APB_GADS_BIN}" ${GADS_EXTRA_ARGS} --customer "$CUSTOMER" playbook search-term-analysis --lookback-days "$LOOKBACK" 2>/dev/null || true)"; audit_record search-term-analysis "$out"
out="$(audit_selected search-term-cleanup && "${APB_GADS_BIN}" ${GADS_EXTRA_ARGS} --customer "$CUSTOMER" playbook search-term-cleanup --lookback-days "$LOOKBACK" 2>/dev/null || true)"; audit_record search-term-cleanup "$out"
out="$(audit_selected search-term-ngram-audit && "${APB_GADS_BIN}" ${GADS_EXTRA_ARGS} --customer "$CUSTOMER" playbook search-term-ngram-audit --lookback-days "$LOOKBACK" 2>/dev/null || true)"; audit_record search-term-ngram-audit "$out"
out="$(audit_selected search-term-promotion && "${APB_GADS_BIN}" ${GADS_EXTRA_ARGS} --customer "$CUSTOMER" playbook search-term-promotion --lookback-days "$LOOKBACK" 2>/dev/null || true)"; audit_record search-term-promotion "$out"
out="$(audit_selected seasonality-overview && "${APB_GADS_BIN}" ${GADS_EXTRA_ARGS} --customer "$CUSTOMER" playbook seasonality-overview --lookback-days "$LOOKBACK" 2>/dev/null || true)"; audit_record seasonality-overview "$out"
out="$(audit_selected shopping-feed-segmentation-audit && "${APB_GADS_BIN}" ${GADS_EXTRA_ARGS} --customer "$CUSTOMER" playbook shopping-feed-segmentation-audit --lookback-days "$LOOKBACK" 2>/dev/null || true)"; audit_record shopping-feed-segmentation-audit "$out"
out="$(audit_selected smart-bidding-readiness && "${APB_GADS_BIN}" ${GADS_EXTRA_ARGS} --customer "$CUSTOMER" playbook smart-bidding-readiness --lookback-days "$LOOKBACK" 2>/dev/null || true)"; audit_record smart-bidding-readiness "$out"
out="$(audit_selected targeting-coverage && "${APB_GADS_BIN}" ${GADS_EXTRA_ARGS} --customer "$CUSTOMER" playbook targeting-coverage --lookback-days "$LOOKBACK" 2>/dev/null || true)"; audit_record targeting-coverage "$out"
out="$(audit_selected waste-audit && "${APB_GADS_BIN}" ${GADS_EXTRA_ARGS} --customer "$CUSTOMER" playbook waste-audit --lookback-days "$LOOKBACK" 2>/dev/null || true)"; audit_record waste-audit "$out"
out="$(audit_selected waste-cluster-audit && "${APB_GADS_BIN}" ${GADS_EXTRA_ARGS} --customer "$CUSTOMER" playbook waste-cluster-audit --lookback-days "$LOOKBACK" 2>/dev/null || true)"; audit_record waste-cluster-audit "$out"
out="$(audit_selected weekly-audit && "${APB_GADS_BIN}" ${GADS_EXTRA_ARGS} --customer "$CUSTOMER" playbook weekly-audit --lookback-days "$LOOKBACK" 2>/dev/null || true)"; audit_record weekly-audit "$out"

audit_index audit-full
