#!/usr/bin/env bash
# GENERATED by gen_scripts.py — do not hand-edit.
# name: audit-signal
# binary: apb-gads
# tier: audit
# cadence: on-demand
# description: GENERATED read-only audit bundle — runs the 4 apb-gads 'signal' diagnostic playbooks into a timestamped results dir + index.md. --only <slug,...> and --lookback supported. Zero API mutations.
# writes: never
set -euo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib/common.sh
source "${HERE}/lib/common.sh"

WATCH_NAME="audit-signal"
LOOKBACK=30
AUDIT_ONLY=""
_args=()
while [ "$#" -gt 0 ]; do
  case "$1" in
    --only) AUDIT_ONLY="${2:?--only needs a value}"; shift 2 ;;
    --only=*) AUDIT_ONLY="${1#*=}"; shift ;;
    -h|--help) audit_usage audit-signal; exit 0 ;;
    *) _args+=("$1"); shift ;;
  esac
done
parse_common_args "${_args[@]}"
audit_begin audit-signal

out="$(audit_selected anomaly-detection && "${APB_GADS_BIN}" ${GADS_EXTRA_ARGS} --customer "$CUSTOMER" playbook anomaly-detection --lookback-days "$LOOKBACK" 2>/dev/null || true)"; audit_record anomaly-detection "$out"
out="$(audit_selected brand-exclusion-audit && "${APB_GADS_BIN}" ${GADS_EXTRA_ARGS} --customer "$CUSTOMER" playbook brand-exclusion-audit --lookback-days "$LOOKBACK" 2>/dev/null || true)"; audit_record brand-exclusion-audit "$out"
out="$(audit_selected policy-compliance && "${APB_GADS_BIN}" ${GADS_EXTRA_ARGS} --customer "$CUSTOMER" playbook policy-compliance --lookback-days "$LOOKBACK" 2>/dev/null || true)"; audit_record policy-compliance "$out"
out="$(audit_selected sandbox-campaign-audit && "${APB_GADS_BIN}" ${GADS_EXTRA_ARGS} --customer "$CUSTOMER" playbook sandbox-campaign-audit --lookback-days "$LOOKBACK" 2>/dev/null || true)"; audit_record sandbox-campaign-audit "$out"

audit_index audit-signal
