#!/usr/bin/env bash
# GENERATED by gen_scripts.py — do not hand-edit.
# name: audit-structure
# binary: apb-gads
# tier: audit
# cadence: on-demand
# description: GENERATED read-only audit bundle — runs the 8 apb-gads 'structure' diagnostic playbooks into a timestamped results dir + index.md. --only <slug,...> and --lookback supported. Zero API mutations.
# writes: never
set -euo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib/common.sh
source "${HERE}/lib/common.sh"

WATCH_NAME="audit-structure"
LOOKBACK=30
AUDIT_ONLY=""
_args=()
while [ "$#" -gt 0 ]; do
  case "$1" in
    --only) AUDIT_ONLY="${2:?--only needs a value}"; shift 2 ;;
    --only=*) AUDIT_ONLY="${1#*=}"; shift ;;
    -h|--help) audit_usage audit-structure; exit 0 ;;
    *) _args+=("$1"); shift ;;
  esac
done
parse_common_args "${_args[@]}"
audit_begin audit-structure

out="$(audit_selected account-structure-audit && "${APB_GADS_BIN}" ${GADS_EXTRA_ARGS} --customer "$CUSTOMER" playbook account-structure-audit --lookback-days "$LOOKBACK" 2>/dev/null || true)"; audit_record account-structure-audit "$out"
out="$(audit_selected campaign-cannibalization && "${APB_GADS_BIN}" ${GADS_EXTRA_ARGS} --customer "$CUSTOMER" playbook campaign-cannibalization --lookback-days "$LOOKBACK" 2>/dev/null || true)"; audit_record campaign-cannibalization "$out"
out="$(audit_selected campaign-consolidation-audit && "${APB_GADS_BIN}" ${GADS_EXTRA_ARGS} --customer "$CUSTOMER" playbook campaign-consolidation-audit --lookback-days "$LOOKBACK" 2>/dev/null || true)"; audit_record campaign-consolidation-audit "$out"
out="$(audit_selected campaign-type-fit && "${APB_GADS_BIN}" ${GADS_EXTRA_ARGS} --customer "$CUSTOMER" playbook campaign-type-fit --lookback-days "$LOOKBACK" 2>/dev/null || true)"; audit_record campaign-type-fit "$out"
out="$(audit_selected expansion-readiness && "${APB_GADS_BIN}" ${GADS_EXTRA_ARGS} --customer "$CUSTOMER" playbook expansion-readiness --lookback-days "$LOOKBACK" 2>/dev/null || true)"; audit_record expansion-readiness "$out"
out="$(audit_selected experiment-readiness && "${APB_GADS_BIN}" ${GADS_EXTRA_ARGS} --customer "$CUSTOMER" playbook experiment-readiness --lookback-days "$LOOKBACK" 2>/dev/null || true)"; audit_record experiment-readiness "$out"
out="$(audit_selected naming-convention-audit && "${APB_GADS_BIN}" ${GADS_EXTRA_ARGS} --customer "$CUSTOMER" playbook naming-convention-audit --lookback-days "$LOOKBACK" 2>/dev/null || true)"; audit_record naming-convention-audit "$out"
out="$(audit_selected shopping-feed-segmentation-audit && "${APB_GADS_BIN}" ${GADS_EXTRA_ARGS} --customer "$CUSTOMER" playbook shopping-feed-segmentation-audit --lookback-days "$LOOKBACK" 2>/dev/null || true)"; audit_record shopping-feed-segmentation-audit "$out"

audit_index audit-structure
