#!/usr/bin/env bash
# GENERATED by gen_scripts.py — do not hand-edit.
# name: audit-bidding
# binary: apb-gads
# tier: audit
# cadence: on-demand
# description: GENERATED read-only audit bundle — runs the 14 apb-gads 'bidding' diagnostic playbooks into a timestamped results dir + index.md. --only <slug,...> and --lookback supported. Zero API mutations.
# writes: never
set -euo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib/common.sh
source "${HERE}/lib/common.sh"

WATCH_NAME="audit-bidding"
LOOKBACK=30
AUDIT_ONLY=""
_args=()
while [ "$#" -gt 0 ]; do
  case "$1" in
    --only) AUDIT_ONLY="${2:?--only needs a value}"; shift 2 ;;
    --only=*) AUDIT_ONLY="${1#*=}"; shift ;;
    -h|--help) audit_usage audit-bidding; exit 0 ;;
    *) _args+=("$1"); shift ;;
  esac
done
parse_common_args "${_args[@]}"
audit_begin audit-bidding

out="$(audit_selected bid-strategy-mismatch && "${APB_GADS_BIN}" ${GADS_EXTRA_ARGS} --customer "$CUSTOMER" playbook bid-strategy-mismatch --lookback-days "$LOOKBACK" 2>/dev/null || true)"; audit_record bid-strategy-mismatch "$out"
out="$(audit_selected budget-pacing && "${APB_GADS_BIN}" ${GADS_EXTRA_ARGS} --customer "$CUSTOMER" playbook budget-pacing --lookback-days "$LOOKBACK" 2>/dev/null || true)"; audit_record budget-pacing "$out"
out="$(audit_selected budget-rebalance && "${APB_GADS_BIN}" ${GADS_EXTRA_ARGS} --customer "$CUSTOMER" playbook budget-rebalance --lookback-days "$LOOKBACK" 2>/dev/null || true)"; audit_record budget-rebalance "$out"
out="$(audit_selected campaign-bid-strategy-audit && "${APB_GADS_BIN}" ${GADS_EXTRA_ARGS} --customer "$CUSTOMER" playbook campaign-bid-strategy-audit --lookback-days "$LOOKBACK" 2>/dev/null || true)"; audit_record campaign-bid-strategy-audit "$out"
out="$(audit_selected conversion-tracking-audit && "${APB_GADS_BIN}" ${GADS_EXTRA_ARGS} --customer "$CUSTOMER" playbook conversion-tracking-audit --lookback-days "$LOOKBACK" 2>/dev/null || true)"; audit_record conversion-tracking-audit "$out"
out="$(audit_selected conversion-tracking-check && "${APB_GADS_BIN}" ${GADS_EXTRA_ARGS} --customer "$CUSTOMER" playbook conversion-tracking-check --lookback-days "$LOOKBACK" 2>/dev/null || true)"; audit_record conversion-tracking-check "$out"
out="$(audit_selected conversion-value-gap && "${APB_GADS_BIN}" ${GADS_EXTRA_ARGS} --customer "$CUSTOMER" playbook conversion-value-gap --lookback-days "$LOOKBACK" 2>/dev/null || true)"; audit_record conversion-value-gap "$out"
out="$(audit_selected conversion-value-tier-audit && "${APB_GADS_BIN}" ${GADS_EXTRA_ARGS} --customer "$CUSTOMER" playbook conversion-value-tier-audit --lookback-days "$LOOKBACK" 2>/dev/null || true)"; audit_record conversion-value-tier-audit "$out"
out="$(audit_selected geo-bid-drift-audit && "${APB_GADS_BIN}" ${GADS_EXTRA_ARGS} --customer "$CUSTOMER" playbook geo-bid-drift-audit --lookback-days "$LOOKBACK" 2>/dev/null || true)"; audit_record geo-bid-drift-audit "$out"
out="$(audit_selected qs-cpc-tax && "${APB_GADS_BIN}" ${GADS_EXTRA_ARGS} --customer "$CUSTOMER" playbook qs-cpc-tax --lookback-days "$LOOKBACK" 2>/dev/null || true)"; audit_record qs-cpc-tax "$out"
out="$(audit_selected quality-score-audit && "${APB_GADS_BIN}" ${GADS_EXTRA_ARGS} --customer "$CUSTOMER" playbook quality-score-audit --lookback-days "$LOOKBACK" 2>/dev/null || true)"; audit_record quality-score-audit "$out"
out="$(audit_selected quality-score-root-cause && "${APB_GADS_BIN}" ${GADS_EXTRA_ARGS} --customer "$CUSTOMER" playbook quality-score-root-cause --lookback-days "$LOOKBACK" 2>/dev/null || true)"; audit_record quality-score-root-cause "$out"
out="$(audit_selected roas-nudge-recommendation && "${APB_GADS_BIN}" ${GADS_EXTRA_ARGS} --customer "$CUSTOMER" playbook roas-nudge-recommendation --lookback-days "$LOOKBACK" 2>/dev/null || true)"; audit_record roas-nudge-recommendation "$out"
out="$(audit_selected smart-bidding-readiness && "${APB_GADS_BIN}" ${GADS_EXTRA_ARGS} --customer "$CUSTOMER" playbook smart-bidding-readiness --lookback-days "$LOOKBACK" 2>/dev/null || true)"; audit_record smart-bidding-readiness "$out"

audit_index audit-bidding
