#!/usr/bin/env bash
# GENERATED by gen_scripts.py — do not hand-edit.
# name: audit-audience
# binary: apb-gads
# tier: audit
# cadence: on-demand
# description: GENERATED read-only audit bundle — runs the 11 apb-gads 'audience' diagnostic playbooks into a timestamped results dir + index.md. --only <slug,...> and --lookback supported. Zero API mutations.
# writes: never
set -euo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib/common.sh
source "${HERE}/lib/common.sh"

WATCH_NAME="audit-audience"
LOOKBACK=30
AUDIT_ONLY=""
_args=()
while [ "$#" -gt 0 ]; do
  case "$1" in
    --only) AUDIT_ONLY="${2:?--only needs a value}"; shift 2 ;;
    --only=*) AUDIT_ONLY="${1#*=}"; shift ;;
    -h|--help) audit_usage audit-audience; exit 0 ;;
    *) _args+=("$1"); shift ;;
  esac
done
parse_common_args "${_args[@]}"
audit_begin audit-audience

out="$(audit_selected audience-burnout-detection && "${APB_GADS_BIN}" ${GADS_EXTRA_ARGS} --customer "$CUSTOMER" playbook audience-burnout-detection --lookback-days "$LOOKBACK" 2>/dev/null || true)"; audit_record audience-burnout-detection "$out"
out="$(audit_selected audience-performance && "${APB_GADS_BIN}" ${GADS_EXTRA_ARGS} --customer "$CUSTOMER" playbook audience-performance --lookback-days "$LOOKBACK" 2>/dev/null || true)"; audit_record audience-performance "$out"
out="$(audit_selected competitor-pressure && "${APB_GADS_BIN}" ${GADS_EXTRA_ARGS} --customer "$CUSTOMER" playbook competitor-pressure --lookback-days "$LOOKBACK" 2>/dev/null || true)"; audit_record competitor-pressure "$out"
out="$(audit_selected cross-network-performance && "${APB_GADS_BIN}" ${GADS_EXTRA_ARGS} --customer "$CUSTOMER" playbook cross-network-performance --lookback-days "$LOOKBACK" 2>/dev/null || true)"; audit_record cross-network-performance "$out"
out="$(audit_selected dayparting-analysis && "${APB_GADS_BIN}" ${GADS_EXTRA_ARGS} --customer "$CUSTOMER" playbook dayparting-analysis --lookback-days "$LOOKBACK" 2>/dev/null || true)"; audit_record dayparting-analysis "$out"
out="$(audit_selected device-performance && "${APB_GADS_BIN}" ${GADS_EXTRA_ARGS} --customer "$CUSTOMER" playbook device-performance --lookback-days "$LOOKBACK" 2>/dev/null || true)"; audit_record device-performance "$out"
out="$(audit_selected geo-performance && "${APB_GADS_BIN}" ${GADS_EXTRA_ARGS} --customer "$CUSTOMER" playbook geo-performance --lookback-days "$LOOKBACK" 2>/dev/null || true)"; audit_record geo-performance "$out"
out="$(audit_selected impression-share-loss && "${APB_GADS_BIN}" ${GADS_EXTRA_ARGS} --customer "$CUSTOMER" playbook impression-share-loss --lookback-days "$LOOKBACK" 2>/dev/null || true)"; audit_record impression-share-loss "$out"
out="$(audit_selected placement-leakage-audit && "${APB_GADS_BIN}" ${GADS_EXTRA_ARGS} --customer "$CUSTOMER" playbook placement-leakage-audit --lookback-days "$LOOKBACK" 2>/dev/null || true)"; audit_record placement-leakage-audit "$out"
out="$(audit_selected seasonality-overview && "${APB_GADS_BIN}" ${GADS_EXTRA_ARGS} --customer "$CUSTOMER" playbook seasonality-overview --lookback-days "$LOOKBACK" 2>/dev/null || true)"; audit_record seasonality-overview "$out"
out="$(audit_selected targeting-coverage && "${APB_GADS_BIN}" ${GADS_EXTRA_ARGS} --customer "$CUSTOMER" playbook targeting-coverage --lookback-days "$LOOKBACK" 2>/dev/null || true)"; audit_record targeting-coverage "$out"

audit_index audit-audience
